# Select a Message by its short name (MsgType)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX orch: <http://fixprotocol.io/2016/orchestra#> 

SELECT ?name ?description
WHERE {
	?message rdfs:label ?name;
		rdf:type orch:Message;
		orch:hasShortName "CQ" .
	OPTIONAL {?message rdfs:comment ?description .}
}
