# Select components and messages that use a message entity

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX orch: <http://fixprotocol.io/2016/orchestra#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?name ?type ?description
WHERE {
	?entity rdfs:label ?name;
		rdf:type ?type;
		orch:has ?member .
	FILTER(?type != owl:NamedIndividual)
	OPTIONAL {?entity rdfs:comment ?description .}
	?member rdfs:label "PegInstructions" .
}