# Select components and fields contained by a message entity

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX orch: <http://fixprotocol.io/2016/orchestra#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?name ?type ?description
WHERE {
	?entity orch:has ?member;
		rdfs:label "IOI" .
	?member rdfs:label ?name;
		rdf:type ?type .
	FILTER(?type != owl:NamedIndividual)
	OPTIONAL {?member rdfs:comment ?description .}
}